### ISSUE TITLE
module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by baqwas** [edgeimpulse/firmware-sony-spresense#3]
Trying to flash firmware after downloading zip archive sony-spresense.

The output is:
```
$ ./flash_linux.sh
Checking Python dependencies...
Checking Python dependencies OK

Flashing board... 

Using device /dev/ttyUSB0
>>> Install files ...
install -b 921600
Install /home/reza/Downloads/IoT/Spresense/sony-spresense/edge_impulse_firmware.spk
|0%-----------------------------50%------------------------------100%|
Traceback (most recent call last):
  File "/home/reza/Downloads/IoT/Spresense/sony-spresense/flash_writer.py", line 716, in <module>
    sys.exit(main())
  File "/home/reza/Downloads/IoT/Spresense/sony-spresense/flash_writer.py", line 684, in main
    writer.install_files(ConfigArgs.PACKAGE_NAME, "install")
  File "/home/reza/Downloads/IoT/Spresense/sony-spresense/flash_writer.py", line 592, in install_files
    modem.send(bin)
  File "/home/reza/Downloads/IoT/Spresense/sony-spresense/xmodem.py", line 532, in send
    if isinstance(callback, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'
```

The working folder has:
```
$ ls -l
total 476
-rw-rw-r-- 1 reza reza    981 Jul 12 21:45 '=2.7.0'
-rw-rw-r-- 1 reza reza    231 Jul 12 21:45 '=3.4'
-rw-r--r-- 1 reza reza 410880 Apr 13 20:48  edge_impulse_firmware.spk
-rwxr-xr-x 1 reza reza    999 Mar  9 21:26  flash_linux.sh
-rwxr-xr-x 1 reza reza    999 Mar  9 21:26  flash_mac.command
-rw-r--r-- 1 reza reza    654 Mar  9 21:26  flash_windows.bat
-rwxr-xr-x 1 reza reza  23232 Mar  9 21:26  flash_writer.py
drwxrwxr-x 2 reza reza   4096 Jul 12 21:43  __pycache__
-rw-r--r-- 1 reza reza  22076 Mar  9 21:26  xmodem.py
```
Using instructions for **Sony Spresense** at [web site](https://docs.edgeimpulse.com/docs/development-platforms/officially-supported-mcu-targets/sony-spresense).

Would appreciate some guidance on resolving this anomaly. Thanks.

Kind regards.

**Comment by mmajchrzycki** [comment]
Hi @baqwas,
The issue has been fixed in the [latest release](https://github.com/edgeimpulse/firmware-sony-spresense/commit/6b9b56b5d255c99d1f8546109ead2851936ab76d)
